Adjust for missing author info
Fixes error that occurs when author info is missing

-> In tidy_pubmed_authors() > dplyr::rename()
Error: no applicable method for 'rename' applied to an object of
class "list"